services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siketan_backend
    restart: unless-stopped
    networks:
      - siketan-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: siketan_frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - siketan-network

  nginx:
    image: nginx:alpine
    container_name: nginx_siketan
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - siketan-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: siketan_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - siketan-network

networks:
  siketan-network:
    driver: bridge
