export const PERMISSIONS = {
  // DASHBOARD PERMISSIONS
  DASHBOARD_INDEX: "dashboard_index",

  // STATISTIC PERMISSIONS
  STATISTIC_INDEX: "statistic_index",
  STATISTIC_CREATE: "statistic_create",
  STATISTIC_DETAIL: "statistic_detail",
  STATISTIC_EDIT: "statistic_edit",
  STATISTIC_DELETE: "statistic_delete",
  STATISTIC_REALISASI: "statistic_realisasi",
  STATISTIC_EXPORT: "statistic_export",
  STATISTIC_IMPORT: "statistic_import",

  // TANAMAN PETANI PERMISSIONS
  TANAMAN_PETANI_INDEX: "tanaman_petani_index",
  TANAMAN_PETANI_CREATE: "tanaman_petani_create",
  TANAMAN_PETANI_DETAIL: "tanaman_petani_detail",
  TANAMAN_PETANI_EDIT: "tanaman_petani_edit",
  TANAMAN_PETANI_DELETE: "tanaman_petani_delete",
  TANAMAN_PETANI_IMPORT: "tanaman_petani_import",
  TANAMAN_PETANI_EXPORT: "tanaman_petani_export",

  // DATA PETANI PERMISSIONS
  DATA_PETANI_INDEX: "data_petani_index",
  DATA_PETANI_CREATE: "data_petani_create",
  DATA_PETANI_DETAIL: "data_petani_detail",
  DATA_PETANI_EDIT: "data_petani_edit",
  DATA_PETANI_APPROVE: "data_petani_approve",
  DATA_PETANI_DELETE: "data_petani_delete",
  DATA_PETANI_IMPORT: "data_petani_import",

  // BERITA PETANI PERMISSIONS
  BERITA_PETANI_INDEX: "berita_petani_index",
  BERITA_PETANI_CREATE: "berita_petani_create",
  BERITA_PETANI_DETAIL: "berita_petani_detail",
  BERITA_PETANI_EDIT: "berita_petani_edit",
  BERITA_PETANI_DELETE: "berita_petani_delete",

  // ACARA PETANI PERMISSIONS
  ACARA_PETANI_INDEX: "acara_petani_index",
  ACARA_PETANI_CREATE: "acara_petani_create",
  ACARA_PETANI_DETAIL: "acara_petani_detail",
  ACARA_PETANI_EDIT: "acara_petani_edit",
  ACARA_PETANI_DELETE: "acara_petani_delete",

  // TOKO PETANI PERMISSIONS
  TOKO_PETANI_INDEX: "toko_petani_index",
  TOKO_PETANI_CREATE: "toko_petani_create",
  TOKO_PETANI_DETAIL: "toko_petani_detail",
  TOKO_PETANI_EDIT: "toko_petani_edit",
  TOKO_PETANI_DELETE: "toko_petani_delete",

  // LIVE CHAT PERMISSIONS
  LIVE_CHAT_INDEX: "live_chat_index",

  // DATA PENYULUH PERMISSIONS
  DATA_PENYULUH_INDEX: "data_penyuluh_index",
  DATA_PENYULUH_CREATE: "data_penyuluh_create",
  DATA_PENYULUH_DETAIL: "data_penyuluh_detail",
  DATA_PENYULUH_EDIT: "data_penyuluh_edit",
  DATA_PENYULUH_IMPORT: "data_penyuluh_import",

  // JURNAL PENYULUH PERMISSIONS
  JURNAL_PENYULUH_INDEX: "jurnal_penyuluh_index",
  JURNAL_PENYULUH_CREATE: "jurnal_penyuluh_create",
  JURNAL_PENYULUH_DETAIL: "jurnal_penyuluh_detail",
  JURNAL_PENYULUH_EDIT: "jurnal_penyuluh_edit",
  JURNAL_PENYULUH_DELETE: "jurnal_penyuluh_delete",

  // VERIFIKASI USER PERMISSIONS
  VERIFIKASI_USER_INDEX: "verifikasi_user_index",
  VERIFIKASI_USER_APPROVE: "verifikasi_user_approve",
  VERIFIKASI_USER_REJECT: "verifikasi_user_reject",

  // UBAH HAK AKSES PERMISSIONS
  UBAH_HAK_AKSES_INDEX: "ubah_hak_akses_index",
  UBAH_HAK_AKSES_EDIT: "ubah_hak_akses_edit",

  // LOG AKTIVITAS PERMISSIONS
  LOG_AKTIVITAS_INDEX: "log_aktivitas_index",

  // DATA SAMPAH PERMISSIONS
  DATA_SAMPAH_INDEX: "data_sampah_index",
  DATA_SAMPAH_RESTORE: "data_sampah_restore",
  DATA_SAMPAH_DELETE: "data_sampah_delete",

  // DATA KELOMPOK PERMISSIONS
  DATA_KELOMPOK_INDEX: "data_kelompok_index",
  DATA_KELOMPOK_EDIT: "data_kelompok_edit",
  DATA_KELOMPOK_DELETE: "data_kelompok_delete",
  DATA_KELOMPOK_IMPORT: "data_kelompok_import",

  // DATA OPERATOR PERMISSIONS
  DATA_OPERATOR_INDEX: "data_operator_index",
  DATA_OPERATOR_CREATE: "data_operator_create",
  DATA_OPERATOR_DETAIL: "data_operator_detail",
  DATA_OPERATOR_EDIT: "data_operator_edit",
  DATA_OPERATOR_DELETE: "data_operator_delete",
  DATA_OPERATOR_IMPORT: "data_operator_import",

  // PROFILE ADMIN PERMISSIONS
  PROFILE_ADMIN_INDEX: "profile_admin_index",

  // PROFILE USER PERMISSIONS
  PROFILE_USER_DETAIL: "profile_user_detail",
  PROFILE_USER_EDIT: "profile_user_edit",

  // ISI FORM PERMISSIONS
  ISI_FORM_CREATE: "isi_form_create",
  ISI_FORM_DETAIL: "isi_form_detail",
} as const;

export type PermissionType = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Permission Groups
export const PERMISSION_GROUPS = {
  DASHBOARD: [PERMISSIONS.DASHBOARD_INDEX],

  STATISTICS: [
    PERMISSIONS.STATISTIC_INDEX,
    PERMISSIONS.STATISTIC_CREATE,
    PERMISSIONS.STATISTIC_DETAIL,
    PERMISSIONS.STATISTIC_EDIT,
    PERMISSIONS.STATISTIC_DELETE,
    PERMISSIONS.STATISTIC_REALISASI,
    PERMISSIONS.STATISTIC_EXPORT,
    PERMISSIONS.STATISTIC_IMPORT,
  ],

  DATA_PETANI: [
    PERMISSIONS.DATA_PETANI_INDEX,
    PERMISSIONS.DATA_PETANI_CREATE,
    PERMISSIONS.DATA_PETANI_DETAIL,
    PERMISSIONS.DATA_PETANI_EDIT,
    PERMISSIONS.DATA_PETANI_APPROVE,
    PERMISSIONS.DATA_PETANI_DELETE,
    PERMISSIONS.DATA_PETANI_IMPORT,
  ],

  TANAMAN_PETANI: [
    PERMISSIONS.TANAMAN_PETANI_INDEX,
    PERMISSIONS.TANAMAN_PETANI_CREATE,
    PERMISSIONS.TANAMAN_PETANI_DETAIL,
    PERMISSIONS.TANAMAN_PETANI_EDIT,
    PERMISSIONS.TANAMAN_PETANI_DELETE,
    PERMISSIONS.TANAMAN_PETANI_IMPORT,
    PERMISSIONS.TANAMAN_PETANI_EXPORT,
  ],

  BERITA_PETANI: [
    PERMISSIONS.BERITA_PETANI_INDEX,
    PERMISSIONS.BERITA_PETANI_CREATE,
    PERMISSIONS.BERITA_PETANI_DETAIL,
    PERMISSIONS.BERITA_PETANI_EDIT,
    PERMISSIONS.BERITA_PETANI_DELETE,
  ],

  ACARA_PETANI: [
    PERMISSIONS.ACARA_PETANI_INDEX,
    PERMISSIONS.ACARA_PETANI_CREATE,
    PERMISSIONS.ACARA_PETANI_DETAIL,
    PERMISSIONS.ACARA_PETANI_EDIT,
    PERMISSIONS.ACARA_PETANI_DELETE,
  ],

  TOKO_PETANI: [
    PERMISSIONS.TOKO_PETANI_INDEX,
    PERMISSIONS.TOKO_PETANI_CREATE,
    PERMISSIONS.TOKO_PETANI_DETAIL,
    PERMISSIONS.TOKO_PETANI_EDIT,
    PERMISSIONS.TOKO_PETANI_DELETE,
  ],

  LIVE_CHAT: [PERMISSIONS.LIVE_CHAT_INDEX],

  DATA_PENYULUH: [
    PERMISSIONS.DATA_PENYULUH_INDEX,
    PERMISSIONS.DATA_PENYULUH_CREATE,
    PERMISSIONS.DATA_PENYULUH_DETAIL,
    PERMISSIONS.DATA_PENYULUH_EDIT,
    PERMISSIONS.DATA_PENYULUH_IMPORT,
  ],

  JURNAL_PENYULUH: [
    PERMISSIONS.JURNAL_PENYULUH_INDEX,
    PERMISSIONS.JURNAL_PENYULUH_CREATE,
    PERMISSIONS.JURNAL_PENYULUH_DETAIL,
    PERMISSIONS.JURNAL_PENYULUH_EDIT,
    PERMISSIONS.JURNAL_PENYULUH_DELETE,
  ],

  VERIFIKASI_USER: [
    PERMISSIONS.VERIFIKASI_USER_INDEX,
    PERMISSIONS.VERIFIKASI_USER_APPROVE,
    PERMISSIONS.VERIFIKASI_USER_REJECT,
  ],

  UBAH_HAK_AKSES: [
    PERMISSIONS.UBAH_HAK_AKSES_INDEX,
    PERMISSIONS.UBAH_HAK_AKSES_EDIT,
  ],

  LOG_AKTIVITAS: [PERMISSIONS.LOG_AKTIVITAS_INDEX],

  DATA_SAMPAH: [
    PERMISSIONS.DATA_SAMPAH_INDEX,
    PERMISSIONS.DATA_SAMPAH_RESTORE,
    PERMISSIONS.DATA_SAMPAH_DELETE,
  ],

  DATA_KELOMPOK: [
    PERMISSIONS.DATA_KELOMPOK_INDEX,
    PERMISSIONS.DATA_KELOMPOK_EDIT,
    PERMISSIONS.DATA_KELOMPOK_DELETE,
    PERMISSIONS.DATA_KELOMPOK_IMPORT,
  ],

  DATA_OPERATOR: [
    PERMISSIONS.DATA_OPERATOR_INDEX,
    PERMISSIONS.DATA_OPERATOR_CREATE,
    PERMISSIONS.DATA_OPERATOR_DETAIL,
    PERMISSIONS.DATA_OPERATOR_EDIT,
    PERMISSIONS.DATA_OPERATOR_DELETE,
    PERMISSIONS.DATA_OPERATOR_IMPORT,
  ],

  PROFILE_ADMIN: [PERMISSIONS.PROFILE_ADMIN_INDEX],

  PROFILE_USER: [
    PERMISSIONS.PROFILE_USER_DETAIL,
    PERMISSIONS.PROFILE_USER_EDIT,
  ],

  ISI_FORM: [PERMISSIONS.ISI_FORM_CREATE, PERMISSIONS.ISI_FORM_DETAIL],
};
